"""Classifies/answers form fields FormFiller doesn't structurally know (ADR-0031).

A single, shared component -- not per-``FormFiller`` logic (ADR-0029's
``FormFiller`` stays scoped to exactly what ADR-0028 defined: fills the
fields it knows, declares them). The four answering categories below are
properties of *the question being asked*, not of which ATS platform is
asking it -- a work-authorization question means the same thing on
Greenhouse or Lever. Splitting this logic per-platform would risk the one
guarantee that must never vary (the EEOC absolute) drifting or being
silently dropped in one platform's copy; keeping it in one place, tested
once, means every platform gets the same guarantee by construction, not by
discipline.

**Deterministic pattern/template matching, not a live model call --
deliberately, for now.** EEOC self-identification questions follow legally
standardized (OFCCP-mandated) boilerplate wording across virtually every
US employer; common legal-status questions (work authorization,
sponsorship) are similarly conventional. That makes template/keyword
matching a real, defensible first approach, not a shortcut -- the same
"prove the cheap thing first" discipline this project applied to Category
4's dropdown matching, now generalized to Categories 1 and 2 as well. A
question whose phrasing doesn't match any known template is **refused, not
guessed at** -- classification failure fails toward the safe category
(EEOC when genuinely ambiguous with a factual reading; Category 3's
"human must author this" as the default fallback for anything unmatched),
never toward a confident wrong answer. A real, LLM-backed classifier
remains a named, deferred escalation if real-world use shows
template-matching insufficient -- not built now, not assumed necessary.

**Scope of this module, stated plainly:** this classifies and answers a
question in isolation, given its text and a :class:`~career_agent.domain.
models.MasterProfile`. It does **not** yet drive a live page -- wiring this
into ``BrowserApplicator.submit()`` (wait for a human on Category 1
decline, on Category 2 capture, on Category 3 authorship; fill Category 2
answers and Category 4 dropdown selections into the real DOM) is real,
separate, deliberately deferred future work, the same "prove the mechanism
in isolation first, wire it into the live flow as its own later step"
sequencing this project used for ``ResumeTailoringPipeline`` (ADR-0023)
before ``SubmissionPipeline`` (ADR-0024) wired a real ``Applicator`` in.

Adversarial test matrix for this module was drafted by the user, not
generated by the agent implementing against it -- the same "the person
best positioned to know what a genuine near-miss looks like should write
the cases" discipline as the truthfulness gate's 12-case matrix (ADR-0016)
and the HN held-candidate matrix (ADR-0013). Twenty cases across four
categories; see ``tests/agents/test_question_answerer.py``.
"""

from __future__ import annotations

import re
from enum import StrEnum

from pydantic import BaseModel, Field

from career_agent.domain.models import MasterProfile

# ---------------------------------------------------------------------------
# EEOC absolute (Category 1): known, legally-standardized boilerplate
# patterns. Matching here means "refuse/pause," never "answer."
# ---------------------------------------------------------------------------

_EEOC_PATTERNS = [
    re.compile(r"\bgender\b", re.IGNORECASE),
    re.compile(r"\brace\b", re.IGNORECASE),
    re.compile(r"\bethnicity\b", re.IGNORECASE),
    re.compile(r"\bhispanic\b", re.IGNORECASE),
    re.compile(r"\blatino\b", re.IGNORECASE),
    re.compile(r"\bveteran\b", re.IGNORECASE),
    re.compile(r"\bprotected\s+veteran\b", re.IGNORECASE),
    re.compile(r"\bdisabilit(y|ies)\b", re.IGNORECASE),
    re.compile(r"\bself[\s-]?identif", re.IGNORECASE),
    re.compile(r"\bvoluntary\s+self", re.IGNORECASE),
    re.compile(r"\btransgender\b", re.IGNORECASE),
    re.compile(r"\bsexual\s+orientation\b", re.IGNORECASE),
]

# A factual-shaped question that is actually asking about EEOC-protected
# class membership, not eligibility -- phrased with "class"/"protected"
# language layered on top of an otherwise yes/no shape (Case 1b).
_EEOC_CLASS_MEMBERSHIP_PATTERN = re.compile(
    r"\b(protected\s+class|protected\s+veteran\s+class|member\s+of\s+a\s+"
    r"protected)\b",
    re.IGNORECASE,
)

# ---------------------------------------------------------------------------
# Category 2: narrow, known templates for LegalStatusSection's two fields.
# Each template maps to (field name, is_negated). A question that doesn't
# match closely enough refuses rather than guesses.
# ---------------------------------------------------------------------------

_WORK_AUTH_TEMPLATE = re.compile(
    r"(are you|do you have).{0,60}(legally\s+)?authorized\s+to\s+work",
    re.IGNORECASE,
)
_WORK_AUTH_NEGATED_TEMPLATE = re.compile(
    r"(do you not|are you not).{0,60}(legally\s+)?authorized\s+to\s+work",
    re.IGNORECASE,
)
_SPONSORSHIP_TEMPLATE = re.compile(
    r"(will you|do you).{0,40}require.{0,20}sponsorship", re.IGNORECASE
)
_SPONSORSHIP_NEGATED_TEMPLATE = re.compile(
    r"(will you not|do you not).{0,40}require.{0,20}sponsorship", re.IGNORECASE
)

# A compound question asking about both facts at once (Case 2a) -- refuse
# rather than confidently answer only the half that matched.
_COMPOUND_CONNECTOR = re.compile(
    r"\band\b.{0,60}(sponsorship|authorized)", re.IGNORECASE
)

# Non-boolean legal-adjacent questions (durations, dates) that sound
# legal-status-shaped but have no LegalStatusSection field to answer them
# from -- refuse rather than invent a number (Case 2d).
_NON_BOOLEAN_LEGAL_PATTERN = re.compile(
    r"\bhow\s+(many|long|much)\b", re.IGNORECASE
)

# A "how many/long" question that also names a legal-status topic (Case
# 2d): recognized as belonging to Category 2's topic area specifically so
# _NON_BOOLEAN_LEGAL_PATTERN's refusal inside answer_factual_question
# actually fires, rather than silently falling through to Category 3
# where the same refusal would happen for a different (unrelated) reason.
_LEGAL_STATUS_TOPIC_PATTERN = re.compile(
    r"\b(sponsorship|work\s+authorization|visa|authorized\s+to\s+work)\b",
    re.IGNORECASE,
)


class QuestionCategory(StrEnum):
    """Which of the four answering categories a real form field falls into."""

    EEOC = "eeoc"
    FACTUAL = "factual"
    SUBJECTIVE = "subjective"
    DROPDOWN = "dropdown"


class MissingLegalStatusFactError(Exception):
    """``MasterProfile.legal_status`` doesn't have this fact captured yet.

    Raised instead of defaulting or inferring -- the same "cannot proceed
    without this, ask the human explicitly" shape as
    :class:`~career_agent.agents.resume.generator.MissingSummaryError`.
    ``None`` on a :class:`~career_agent.domain.models.LegalStatusSection`
    field means "not yet captured," never "no" -- this error is what
    keeps that distinction load-bearing rather than a type-level
    decoration nobody actually checks.
    """


class AmbiguousQuestionError(Exception):
    """A question matched no known template closely enough to answer safely.

    Distinct from a classification failure being silently swallowed --
    this names exactly what happened (no confident template match) so a
    human reviewing the refusal knows the system declined to guess, rather
    than assuming it tried and got it right.
    """


class DropdownMatchResult(BaseModel):
    """How confidently a profile value maps to one real dropdown option.

    A similarity judgment, not a truth judgment (Category 4), deliberately
    kept a distinct type from :class:`~career_agent.core.interfaces.
    ClaimVerdict` (which answers a different question: is this claim
    entailed by evidence).
    """

    matched_option: str | None
    similarity: float = Field(ge=0.0, le=1.0)
    candidate_options_considered: list[str]


class AmbiguousDropdownMatchError(Exception):
    """No live dropdown option matched the profile value confidently enough.

    Distinct from :class:`~career_agent.agents.apply.browser_applicator.
    UnsupportedFormFieldsError` on purpose: that error means "I don't know
    this field exists at all." This means "I know this field and have a
    real value for it, but can't confidently map that value to any option
    this specific form actually offers" -- a different failure mode a
    human needs to be able to tell apart, so they know whether to fix
    their profile data or just complete this one field by hand. A
    close-but-wrong dropdown selection is worse than a blank field: it
    submits false information that looks deliberate (Case 4c).
    """


def classify_question(question_text: str) -> QuestionCategory:
    """Classify one real application question into one of the four categories.

    Classification is based on *what the question is actually asking*, not
    surface grammatical shape (Case 1b: a yes/no question about protected-
    class membership is EEOC, not factual, despite matching work-
    authorization's yes/no shape). When genuinely ambiguous between EEOC
    and factual readings, the tie-break goes to EEOC -- refuse, never
    auto-answer (Case 1c). Anything matching no known template at all
    falls through to :attr:`QuestionCategory.SUBJECTIVE` -- the safe
    default, since routing an unrecognized question to a human for direct
    authorship can never fabricate or misrepresent anything, unlike a
    false positive in either other direction.
    """
    if _EEOC_CLASS_MEMBERSHIP_PATTERN.search(question_text):
        return QuestionCategory.EEOC
    if any(pattern.search(question_text) for pattern in _EEOC_PATTERNS):
        return QuestionCategory.EEOC
    if _matches_legal_status_template(question_text):
        return QuestionCategory.FACTUAL
    return QuestionCategory.SUBJECTIVE


def _matches_legal_status_template(question_text: str) -> bool:
    if (
        _NON_BOOLEAN_LEGAL_PATTERN.search(question_text)
        and _LEGAL_STATUS_TOPIC_PATTERN.search(question_text)
    ):
        # Not actually answerable (Case 2d) -- but recognized as *this
        # category's* topic so answer_factual_question's own refusal
        # fires for the right, specific reason, rather than the question
        # silently falling through to Category 3 for an unrelated one.
        return True
    return bool(
        _WORK_AUTH_TEMPLATE.search(question_text)
        or _WORK_AUTH_NEGATED_TEMPLATE.search(question_text)
        or _SPONSORSHIP_TEMPLATE.search(question_text)
        or _SPONSORSHIP_NEGATED_TEMPLATE.search(question_text)
    )


def answer_eeoc_question(question_text: str, response: bool | None) -> bool | None:
    """The EEOC absolute: never auto-fill, never suggest-then-confirm.

    Never consults ``MasterProfile`` at all -- not "looked, found nothing,
    refused," but a structural absence of the attempt itself (Case 1d),
    proven the same way ``adapter.calls == []`` proves a real action never
    fired elsewhere in this project. ``response`` is only ever supplied by
    a human's own, unprompted answer (or ``None`` for "declined to
    answer," a complete, valid, terminal outcome -- Case 1e). This
    function's entire job is to *not* look anywhere else for an answer,
    which is why it takes no ``MasterProfile`` parameter at all: the
    absence of that parameter is itself part of the guarantee.
    """
    return response


def answer_factual_question(
    question_text: str, profile: MasterProfile
) -> bool:
    """Answer a Category 2 (profile-groundable factual) question.

    Raises :class:`AmbiguousQuestionError` on a compound question (Case
    2a: never confidently answer only half of a question asking about two
    facts at once) or a non-boolean legal-adjacent question with no
    LegalStatusSection field to answer it from (Case 2d: refusing beats
    inventing a duration). Raises :class:`MissingLegalStatusFactError` if
    the matched fact is ``None`` -- not yet captured, never defaulted.
    Correctly resolves negated phrasing ("do you *not* require
    sponsorship") to the same field with inverted polarity (Case 2b) --
    the single most dangerous failure mode in this category, since a
    confidently *wrong-polarity* answer looks like a normal answer while
    asserting the opposite of what's true.
    """
    if _COMPOUND_CONNECTOR.search(question_text):
        raise AmbiguousQuestionError(
            f"question {question_text!r} appears to ask about more than "
            f"one fact at once -- refusing rather than answering only the "
            f"half that matched"
        )
    if _NON_BOOLEAN_LEGAL_PATTERN.search(question_text):
        raise AmbiguousQuestionError(
            f"question {question_text!r} is not a yes/no question this "
            f"module has a field for -- refusing rather than inventing an "
            f"answer"
        )

    negated = bool(
        _WORK_AUTH_NEGATED_TEMPLATE.search(question_text)
        or _SPONSORSHIP_NEGATED_TEMPLATE.search(question_text)
    )
    if _WORK_AUTH_TEMPLATE.search(question_text) or _WORK_AUTH_NEGATED_TEMPLATE.search(
        question_text
    ):
        fact = profile.legal_status.work_authorized_us
        field_name = "work_authorized_us"
    elif _SPONSORSHIP_TEMPLATE.search(
        question_text
    ) or _SPONSORSHIP_NEGATED_TEMPLATE.search(question_text):
        fact = profile.legal_status.requires_sponsorship
        field_name = "requires_sponsorship"
    else:
        raise AmbiguousQuestionError(
            f"question {question_text!r} did not match any known "
            f"legal-status template -- refusing rather than guessing"
        )

    if fact is None:
        raise MissingLegalStatusFactError(
            f"MasterProfile.legal_status.{field_name} has not been "
            f"captured yet -- ask the human directly before answering "
            f"{question_text!r}, never default or infer"
        )

    return (not fact) if negated else fact


def match_dropdown_option(
    profile_value: str,
    options: list[str],
    *,
    similarity_threshold: float = 0.7,
) -> DropdownMatchResult:
    """Match ``profile_value`` against a live form's real dropdown options.

    Deterministic string similarity, not a model call (Category 4's
    "prove the cheap thing first" design). Picks the highest-similarity
    option only if it clears ``similarity_threshold`` **and** is not
    ambiguously tied with a second, near-identical option (Case 4b: three
    near-identical options -- "B.S.", "BS", "Bachelor's" -- must not have
    one arbitrarily picked over the others). Returns ``matched_option=None``
    when nothing clears the bar (Case 4c: a close-but-wrong match is worse
    than blank) -- callers must raise :class:`AmbiguousDropdownMatchError`
    on that result themselves, so this function stays a pure judgment, not
    a side-effecting refusal.
    """
    normalized_value = _normalize(profile_value)
    scored = sorted(
        (
            (option, _similarity(normalized_value, _normalize(option)))
            for option in options
        ),
        key=lambda pair: pair[1],
        reverse=True,
    )
    if not scored:
        return DropdownMatchResult(
            matched_option=None, similarity=0.0, candidate_options_considered=options
        )

    best_option, best_score = scored[0]
    if best_score < similarity_threshold:
        return DropdownMatchResult(
            matched_option=None,
            similarity=best_score,
            candidate_options_considered=options,
        )

    if len(scored) > 1:
        _, second_score = scored[1]
        if best_score - second_score < 0.05:
            # Near-tie among multiple plausible options -- refuse rather
            # than arbitrarily pick one (Case 4b).
            return DropdownMatchResult(
                matched_option=None,
                similarity=best_score,
                candidate_options_considered=options,
            )

    return DropdownMatchResult(
        matched_option=best_option,
        similarity=best_score,
        candidate_options_considered=options,
    )


_ABBREVIATIONS = {
    "b.s.": "bachelor of science",
    "bs": "bachelor of science",
    "b.a.": "bachelor of arts",
    "ba": "bachelor of arts",
    "m.s.": "master of science",
    "ms": "master of science",
    "m.a.": "master of arts",
    "ma": "master of arts",
    "phd": "doctor of philosophy",
    "ph.d.": "doctor of philosophy",
}


def _normalize(value: str) -> str:
    lowered = value.strip().lower()
    lowered = _ABBREVIATIONS.get(lowered, lowered)
    lowered = re.sub(r"[^\w\s]", " ", lowered)
    lowered = re.sub(r"\bbachelor s\b", "bachelor of science", lowered)
    lowered = re.sub(r"\s+", " ", lowered).strip()
    return lowered


def _similarity(a: str, b: str) -> float:
    """Token-overlap (Jaccard) similarity -- simple, conservative, no model."""
    tokens_a = set(a.split())
    tokens_b = set(b.split())
    if not tokens_a or not tokens_b:
        return 0.0
    intersection = tokens_a & tokens_b
    union = tokens_a | tokens_b
    return len(intersection) / len(union)
